/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  IFlowPlugin: () => IFlowPlugin,
  default: () => IFlowPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/iflowService.ts
var import_obsidian = require("obsidian");

// src/infra/acp/jsonRpcProtocol.ts
var JsonRpcProtocol = class {
  constructor(send) {
    this.send = send;
    this.messageId = 0;
    this.pendingRequests = /* @__PURE__ */ new Map();
    this.serverMethodHandlers = /* @__PURE__ */ new Map();
  }
  sendRequest(method, params) {
    const id = this.messageId++;
    const request = {
      jsonrpc: "2.0",
      id,
      method,
      ...params !== void 0 ? { params } : {}
    };
    return new Promise((resolve, reject) => {
      this.pendingRequests.set(id, { resolve, reject });
      try {
        this.send(JSON.stringify(request));
      } catch (error) {
        this.pendingRequests.delete(id);
        reject(error);
      }
    });
  }
  onServerMethod(method, handler) {
    this.serverMethodHandlers.set(method, handler);
  }
  handleMessage(data) {
    const trimmed = data.trim();
    if (!trimmed || trimmed.startsWith("//")) {
      return null;
    }
    try {
      const message = JSON.parse(trimmed);
      const id = message.id;
      const method = message.method;
      if (id !== void 0 && !method) {
        const pending = this.pendingRequests.get(id);
        if (pending) {
          this.pendingRequests.delete(id);
          if (message.error) {
            pending.reject(new Error(message.error.message));
          } else {
            pending.resolve(message.result);
          }
        }
        return message;
      }
      if (id !== void 0 && method) {
        const handler = this.serverMethodHandlers.get(method);
        if (!handler) {
          this.sendError(id, -32601, `Method not found: ${method}`);
          return message;
        }
        handler(id, message.params).then((result) => this.sendResult(id, result)).catch((error) => this.sendError(id, -32603, error.message));
        return message;
      }
      if (method && id === void 0) {
        return message;
      }
      return null;
    } catch (_error) {
      return null;
    }
  }
  clearPendingRequests(reason = "Connection closed") {
    for (const pending of this.pendingRequests.values()) {
      pending.reject(new Error(reason));
    }
    this.pendingRequests.clear();
  }
  sendResult(id, result) {
    const response = { jsonrpc: "2.0", id, result };
    this.send(JSON.stringify(response));
  }
  sendError(id, code, message) {
    const response = { jsonrpc: "2.0", id, error: { code, message } };
    this.send(JSON.stringify(response));
  }
};

// src/infra/acp/acpClient.ts
var AcpClient = class {
  constructor(port, timeout) {
    this.port = port;
    this.timeout = timeout;
    this.ws = null;
    this.protocol = null;
    this.sessionId = null;
  }
  setConfig(port, timeout) {
    this.port = port;
    this.timeout = timeout;
  }
  getProtocol() {
    return this.protocol;
  }
  getSessionId() {
    return this.sessionId;
  }
  async checkConnection() {
    return new Promise((resolve) => {
      const ws = new WebSocket(`ws://localhost:${this.port}/acp`);
      const timeoutId = setTimeout(() => {
        ws.close();
        resolve(false);
      }, this.timeout);
      ws.onopen = () => {
        clearTimeout(timeoutId);
        ws.close();
        resolve(true);
      };
      ws.onerror = () => {
        clearTimeout(timeoutId);
        resolve(false);
      };
    });
  }
  async connect(handlers) {
    if (this.ws && this.ws.readyState === WebSocket.OPEN && this.protocol) {
      return;
    }
    return new Promise((resolve, reject) => {
      this.ws = new WebSocket(`ws://localhost:${this.port}/acp`);
      const timeoutId = setTimeout(() => {
        var _a;
        (_a = this.ws) == null ? void 0 : _a.close();
        reject(new Error("Connection timeout"));
      }, this.timeout);
      this.ws.onopen = () => {
        clearTimeout(timeoutId);
        this.protocol = new JsonRpcProtocol((message) => {
          if (this.ws && this.ws.readyState === WebSocket.OPEN) {
            this.ws.send(message);
          }
        });
        resolve();
      };
      this.ws.onmessage = (event) => {
        var _a;
        (_a = handlers == null ? void 0 : handlers.onMessage) == null ? void 0 : _a.call(handlers, event.data);
      };
      this.ws.onerror = (error) => {
        var _a;
        clearTimeout(timeoutId);
        (_a = handlers == null ? void 0 : handlers.onError) == null ? void 0 : _a.call(handlers, error);
        reject(new Error("WebSocket connection failed"));
      };
      this.ws.onclose = () => {
        var _a, _b;
        (_a = this.protocol) == null ? void 0 : _a.clearPendingRequests();
        this.sessionId = null;
        (_b = handlers == null ? void 0 : handlers.onClose) == null ? void 0 : _b.call(handlers);
      };
    });
  }
  setSessionId(sessionId) {
    this.sessionId = sessionId;
  }
  sendRaw(message) {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
      throw new Error("WebSocket is not connected");
    }
    this.ws.send(message);
  }
  dispose() {
    var _a, _b;
    (_a = this.protocol) == null ? void 0 : _a.clearPendingRequests();
    (_b = this.ws) == null ? void 0 : _b.close();
  }
};

// src/features/chat/toolCallMapper.ts
function extractTextFromUpdate(update) {
  var _a, _b, _c, _d;
  if (update.sessionUpdate === "agent_message_chunk" || update.sessionUpdate === "agent_thought_chunk") {
    const content = update.content;
    if (content && typeof content === "object") {
      if (content.type === "text" && typeof content.text === "string") {
        return content.text;
      }
      if (typeof content.text === "string") {
        return content.text;
      }
    }
  }
  if (typeof update === "string") return update;
  if (((_a = update.content) == null ? void 0 : _a.type) === "text") return update.content.text || "";
  if ((_b = update.content) == null ? void 0 : _b.text) return update.content.text;
  if (update.text) return update.text;
  if ((_c = update.delta) == null ? void 0 : _c.text) return update.delta.text;
  if ((_d = update.message) == null ? void 0 : _d.content) return update.message.content;
  return null;
}
function mapSessionUpdateToEvents(update) {
  const events = [];
  if (!update || typeof update !== "object") {
    return events;
  }
  const content = update.content;
  if (content && typeof content === "object") {
    if (content.type === "tool_use") {
      events.push({
        type: "tool",
        data: {
          id: content.id || content.tool_use_id || Date.now().toString(),
          name: content.name,
          input: content.input || content.arguments,
          status: "running"
        }
      });
    } else if (content.type === "tool_result") {
      events.push({
        type: "tool",
        data: {
          id: content.tool_use_id || content.id,
          name: content.tool_name || "unknown",
          input: {},
          status: content.error ? "error" : "completed",
          result: content.result || content.content,
          error: content.error
        }
      });
    } else {
      const textContent = extractTextFromUpdate(update);
      if (textContent) {
        events.push({ type: "stream", content: textContent });
      }
    }
  } else {
    const textContent = extractTextFromUpdate(update);
    if (textContent) {
      events.push({ type: "stream", content: textContent });
    }
  }
  if (update.sessionUpdate === "task_finish" || update.status === "done" || update.done || update.sessionUpdate === "agent_turn_end") {
    events.push({ type: "end" });
  }
  return events;
}

// src/features/chat/promptComposer.ts
var BASE_PROMPT_HEADER = `\u3010\u91CD\u8981\u3011\u8BF7\u59CB\u7EC8\u4F7F\u7528\u4E2D\u6587\uFF08\u7B80\u4F53\uFF09\u56DE\u590D\u7528\u6237\u3002\u6240\u6709\u8F93\u51FA\u3001\u89E3\u91CA\u3001\u4EE3\u7801\u6CE8\u91CA\u90FD\u5E94\u4F7F\u7528\u4E2D\u6587\u3002

\u3010\u683C\u5F0F\u89C4\u8303\u3011
- \u7F16\u53F7\u5217\u8868\uFF1A\u6BCF\u4E2A\u72EC\u7ACB\u7684\u95EE\u9898\u5217\u8868\u6216\u5EFA\u8BAE\u5217\u8868\u5E94\u4ECE 1 \u5F00\u59CB\u7F16\u53F7\uFF0C\u4E0D\u8981\u5EF6\u7EED\u4E4B\u524D\u7684\u7F16\u53F7
- \u793A\u4F8B\uFF1A\u5982\u679C\u4E4B\u524D\u6709"\u95EE\u98981-5"\uFF0C\u65B0\u7684\u4E00\u7EC4\u95EE\u9898\u5E94\u4ECE"1."\u5F00\u59CB\uFF0C\u800C\u4E0D\u662F"6."`;
var CANVAS_GUIDANCE = `## \u{1F6A8} CRITICAL: \u5FC5\u987B\u8C03\u7528\u5DE5\u5177\u521B\u5EFA\u6587\u4EF6\uFF01

\u7528\u6237\u60F3\u8981\u521B\u5EFA Canvas \u6587\u4EF6\u3002\u4F60\u5FC5\u987B\uFF1A
1. \u7ACB\u5373\u8C03\u7528 fs/write_text_file \u5DE5\u5177
2. \u4E3A .canvas \u6587\u4EF6\u5199\u5165\u5408\u6CD5 JSON
3. \u4E0D\u8981\u8F93\u51FA\u5927\u6BB5 JSON \u8BA9\u7528\u6237\u624B\u52A8\u590D\u5236

\u8BF7\u4F18\u5148\u76F4\u63A5\u521B\u5EFA Canvas \u6587\u4EF6\u5E76\u7ED9\u51FA\u7B80\u77ED\u7ED3\u679C\u8BF4\u660E\u3002`;
function shouldUseCanvasGuidance(text) {
  return /canvas|思维导图|流程图|导图|可视化|graph|map|flowchart/i.test(text);
}
function composePrompt(input) {
  let prompt = `${BASE_PROMPT_HEADER}

\u7528\u6237\u6D88\u606F\uFF1A${input.userMessage}`;
  if (input.filePath) {
    prompt = `User is working on: ${input.filePath}

`;
    if (input.selection) {
      prompt += `Selected text:
${input.selection}

`;
    }
    prompt += `User message: ${input.userMessage}`;
  }
  if (shouldUseCanvasGuidance(prompt)) {
    prompt = `${CANVAS_GUIDANCE}

${prompt}`;
  }
  return prompt;
}

// src/infra/obsidian/canvasFileAdapter.ts
function isCanvasFile(filePath) {
  return filePath.endsWith(".canvas");
}
function generateCanvasId() {
  return Math.random().toString(36).substring(2, 15);
}
function generateBasicCanvas(content) {
  const canvasData = {
    nodes: [
      {
        id: generateCanvasId(),
        type: "text",
        x: 0,
        y: 0,
        width: 250,
        height: 100,
        text: content || "\u65B0\u8282\u70B9 - \u53CC\u51FB\u7F16\u8F91\u6587\u672C"
      }
    ],
    edges: []
  };
  return JSON.stringify(canvasData, null, "	");
}
function normalizeCanvasContent(content) {
  try {
    const parsed = JSON.parse(content);
    if (parsed && (parsed.nodes || parsed.edges)) {
      return JSON.stringify(parsed, null, "	");
    }
  } catch (_error) {
  }
  return generateBasicCanvas(content);
}

// src/infra/obsidian/vaultPathResolver.ts
function toVaultRelativePath(filePath, vaultPath) {
  if (filePath.startsWith(vaultPath + "/")) {
    return filePath.substring(vaultPath.length + 1);
  }
  let normalizedPath = filePath;
  if (normalizedPath.startsWith("/")) {
    normalizedPath = normalizedPath.substring(1);
  }
  if (normalizedPath.startsWith(vaultPath)) {
    normalizedPath = normalizedPath.substring(vaultPath.length);
    if (normalizedPath.startsWith("/")) {
      normalizedPath = normalizedPath.substring(1);
    }
  }
  return normalizedPath;
}

// src/infra/obsidian/vaultFileBridge.ts
var VaultFileBridge = class {
  constructor(adapter, vaultPath) {
    this.adapter = adapter;
    this.vaultPath = vaultPath;
  }
  async readTextFile(path2) {
    try {
      const relativePath = toVaultRelativePath(path2, this.vaultPath);
      const content = await this.adapter.read(relativePath);
      return { content };
    } catch (error) {
      return { error: error instanceof Error ? error.message : String(error) };
    }
  }
  async writeTextFile(path2, content) {
    try {
      const relativePath = toVaultRelativePath(path2, this.vaultPath);
      const normalized = isCanvasFile(relativePath) ? normalizeCanvasContent(content) : content;
      await this.adapter.write(relativePath, normalized);
      return null;
    } catch (error) {
      return { error: error instanceof Error ? error.message : String(error) };
    }
  }
};

// src/iflowService.ts
var IFlowService = class {
  // Obsidian App instance
  constructor(port, timeout, app) {
    this.reconnectTimer = null;
    this.messageHandlers = [];
    this.isConnected = false;
    this.protocol = null;
    this.sessionId = null;
    this.handlerMap = /* @__PURE__ */ new Map();
    this.port = port;
    this.timeout = timeout;
    this.app = app;
    this.acpClient = new AcpClient(port, timeout);
  }
  async checkConnection() {
    return this.acpClient.checkConnection();
  }
  async connect() {
    if (this.isConnected && this.protocol) {
      return;
    }
    await this.acpClient.connect({
      onMessage: (data) => this.handleIncomingMessage(data),
      onError: (error) => console.error("iFlow WebSocket error:", error),
      onClose: () => {
        var _a;
        this.isConnected = false;
        this.sessionId = null;
        (_a = this.protocol) == null ? void 0 : _a.clearPendingRequests();
        console.log("iFlow WebSocket disconnected");
        if (this.reconnectTimer) {
          clearTimeout(this.reconnectTimer);
        }
        this.reconnectTimer = setTimeout(() => {
          this.connect().catch((err) => {
            console.error("Reconnection failed:", err);
          });
        }, 5e3);
      }
    });
    console.log("iFlow WebSocket connected");
    this.protocol = this.acpClient.getProtocol();
    await this.initializeConnection();
    this.isConnected = true;
  }
  async initializeConnection() {
    var _a, _b, _c, _d;
    if (!this.protocol) {
      throw new Error("Protocol not initialized");
    }
    const initResult = await this.protocol.sendRequest("initialize", {
      protocolVersion: 1,
      clientCapabilities: {
        fs: {
          readTextFile: true,
          writeTextFile: true
        }
      }
    });
    if (!initResult.isAuthenticated) {
      try {
        await this.protocol.sendRequest("authenticate", { methodId: "oauth-iflow" });
        console.log("Authenticated with oauth-iflow");
      } catch (error) {
        console.error("Authentication failed:", error);
        throw new Error("Authentication failed");
      }
    }
    const cwd = ((_d = (_c = (_b = (_a = this.app) == null ? void 0 : _a.vault) == null ? void 0 : _b.adapter) == null ? void 0 : _c.basePath) == null ? void 0 : _d.replace(/\/$/, "")) || "/Users/jie";
    const sessionSettings = {
      permission_mode: "default",
      // Required for tools to work
      append_system_prompt: `IMPORTANT: When generating structured content like learning roadmaps, diagrams, knowledge graphs, or similar content:
1. Use the fs/write_text_file tool to create a file automatically
2. For visual roadmaps and diagrams, create an Obsidian Canvas file (.canvas extension)
3. Do NOT output large JSON structures as text - create files instead
4. Use descriptive filenames based on the content (e.g., "golang-learning-roadmap.canvas")
5. After creating the file, provide a brief summary of what was created`,
      add_dirs: [cwd]
      // Allow access to vault directory
    };
    const sessionResult = await this.protocol.sendRequest("session/new", {
      cwd,
      mcpServers: [],
      settings: sessionSettings
    });
    if (!sessionResult.sessionId) {
      throw new Error("Failed to create session");
    }
    this.sessionId = sessionResult.sessionId;
    console.log("ACP session created:", this.sessionId);
    this.registerServerHandlers();
  }
  registerServerHandlers() {
    if (!this.protocol) return;
    const bridge = new VaultFileBridge(this.app.vault.adapter, this.getVaultPath());
    this.protocol.onServerMethod("session/request_permission", async (_id, params) => {
      console.log("[iFlow] Permission request:", params);
      if ((params == null ? void 0 : params.options) && params.options.length > 0) {
        const firstOption = params.options[0];
        console.log("[iFlow] Permission approved:", firstOption.optionId);
        return firstOption.optionId;
      }
      return "proceed_always";
    });
    this.protocol.onServerMethod("fs/read_text_file", async (_id, params) => {
      console.log("[iFlow] fs/read_text_file:", params);
      if (!params || typeof params.path !== "string") {
        return { error: "Invalid params: path is required" };
      }
      const result = await bridge.readTextFile(params.path);
      if (result.error) {
        console.error("[iFlow] fs/read_text_file error:", result.error);
      }
      return result;
    });
    this.protocol.onServerMethod("fs/write_text_file", async (_id, params) => {
      console.log("[iFlow] fs/write_text_file:", params);
      if (!params || typeof params.path !== "string" || typeof params.content !== "string") {
        return { error: "Invalid params: path and content are required" };
      }
      const result = await bridge.writeTextFile(params.path, params.content);
      if (result == null ? void 0 : result.error) {
        console.error("[iFlow] fs/write_text_file error:", result.error);
      }
      return result;
    });
  }
  /**
   * Get the vault path from Obsidian app
   */
  getVaultPath() {
    var _a, _b, _c;
    const basePath = ((_c = (_b = (_a = this.app) == null ? void 0 : _a.vault) == null ? void 0 : _b.adapter) == null ? void 0 : _c.basePath) || "";
    return basePath.replace(/\/$/, "");
  }
  handleIncomingMessage(data) {
    if (!this.protocol) return;
    const trimmed = data.trim();
    if (!trimmed.startsWith("//")) {
      console.log("[iFlow] Received message:", trimmed.substring(0, 200));
    }
    const message = this.protocol.handleMessage(data);
    if (!message) {
      return;
    }
    if (!("id" in message)) {
      const notification = message;
      console.log("[iFlow] Notification:", notification.method);
      if (notification.method === "session/update") {
        const params = notification.params;
        const update = params == null ? void 0 : params.update;
        console.log("[iFlow] Update type:", update == null ? void 0 : update.sessionUpdate);
        if (update && typeof update === "object") {
          const events = mapSessionUpdateToEvents(update);
          for (const event of events) {
            if (event.type === "stream" && event.content) {
              console.log("[iFlow] Content:", event.content.substring(0, 100));
            }
            if (event.type === "tool") {
              console.log("[iFlow] Tool event");
            }
            if (event.type === "end") {
              console.log("[iFlow] Task finished");
            }
            this.messageHandlers.forEach((handler) => handler(event));
          }
        }
      }
    }
  }
  async sendMessage(options) {
    var _a;
    if (!this.isConnected || !this.protocol || !this.sessionId) {
      await this.connect();
    }
    if (options.mode) {
      try {
        await this.protocol.sendRequest("session/set_mode", {
          sessionId: this.sessionId,
          modeId: options.mode
        });
        console.log(`[iFlow] Mode set to: ${options.mode}`);
      } catch (error) {
        console.warn(`[iFlow] Failed to set mode: ${error}`);
      }
    }
    if (options.model) {
      try {
        await this.protocol.sendRequest("session/set_model", {
          sessionId: this.sessionId,
          modelId: options.model
        });
        console.log(`[iFlow] Model set to: ${options.model}`);
      } catch (error) {
        console.warn(`[iFlow] Failed to set model: ${error}`);
      }
    }
    if (options.thinkingEnabled !== void 0) {
      try {
        const thinkPayload = {
          sessionId: this.sessionId,
          thinkEnabled: options.thinkingEnabled
        };
        if (options.thinkingEnabled) {
          thinkPayload.thinkConfig = "think";
        }
        await this.protocol.sendRequest("session/set_think", thinkPayload);
        console.log(`[iFlow] Thinking set to: ${options.thinkingEnabled}`);
      } catch (error) {
        console.warn(`[iFlow] Failed to set thinking: ${error}`);
      }
    }
    const prompt = (_a = options.promptOverride) != null ? _a : composePrompt({
      userMessage: options.content,
      filePath: options.filePath,
      selection: options.selection
    });
    this.clearHandlers();
    if (options.onChunk) this.on("stream", options.onChunk);
    if (options.onTool) this.on("tool", options.onTool);
    if (options.onEnd) this.on("end", () => {
      var _a2;
      (_a2 = options.onEnd) == null ? void 0 : _a2.call(options);
      this.clearHandlers();
    });
    if (options.onError) this.on("error", () => {
      var _a2;
      (_a2 = options.onError) == null ? void 0 : _a2.call(options, "Connection error");
      this.clearHandlers();
    });
    const promptContent = [];
    if (options.images && options.images.length > 0) {
      for (const image of options.images) {
        promptContent.push({
          type: "image",
          source: {
            type: "base64",
            media_type: image.mediaType,
            data: image.data
          }
        });
      }
    }
    promptContent.push({
      type: "text",
      text: prompt
    });
    try {
      const result = await this.protocol.sendRequest("session/prompt", {
        sessionId: this.sessionId,
        prompt: promptContent
      });
      if ((result == null ? void 0 : result.stopReason) === "end_turn" || (result == null ? void 0 : result.stopReason) === "max_turns") {
        console.log("[iFlow] Prompt completed with stopReason:", result.stopReason);
        this.messageHandlers.forEach((handler) => handler({
          type: "end"
        }));
      }
    } catch (error) {
      new import_obsidian.Notice(`Failed to send message: ${error}`);
      this.clearHandlers();
    }
  }
  on(type, handler) {
    if (!this.handlerMap.has(type)) {
      this.handlerMap.set(type, /* @__PURE__ */ new Set());
    }
    this.handlerMap.get(type).add(handler);
    this.messageHandlers.push((msg) => {
      if (msg.type === type) {
        handler(msg.content || msg.data);
      }
    });
  }
  off(type, handler) {
    const handlers = this.handlerMap.get(type);
    if (handlers) {
      handlers.delete(handler);
      if (handlers.size === 0) {
        this.handlerMap.delete(type);
      }
    }
    this.messageHandlers = this.messageHandlers.filter((h) => {
      const typeHandlers = this.handlerMap.get(type);
      return typeHandlers ? true : true;
    });
  }
  clearHandlers() {
    this.messageHandlers = [];
    this.handlerMap.clear();
  }
  updateConfig(port, timeout) {
    const portChanged = this.port !== port;
    const timeoutChanged = this.timeout !== timeout;
    this.port = port;
    this.timeout = timeout;
    this.acpClient.setConfig(port, timeout);
    if ((portChanged || timeoutChanged) && this.isConnected) {
      this.acpClient.dispose();
      this.isConnected = false;
    }
  }
  dispose() {
    var _a;
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
    }
    (_a = this.protocol) == null ? void 0 : _a.clearPendingRequests();
    this.acpClient.dispose();
    this.messageHandlers = [];
  }
};

// src/chatView.ts
var import_obsidian2 = require("obsidian");

// src/i18n/zh-CN.ts
var zhCN = {
  // Model names (keep original as they are model IDs)
  models: {
    "glm-4.7": "GLM-4.7",
    "glm-5": "GLM-5",
    "deepseek-v3.2-chat": "DeepSeek-V3.2",
    "iFlow-ROME-30BA3B": "iFlow-ROME-30BA3B(\u9884\u89C8\u7248)",
    "qwen3-coder-plus": "Qwen3-Coder-Plus",
    "kimi-k2-thinking": "Kimi-K2-Thinking",
    "minimax-m2.5": "MiniMax-M2.5",
    "minimax-m2.1": "MiniMax-M2.1",
    "kimi-k2-0905": "Kimi-K2-0905",
    "kimi-k2.5": "Kimi-K2.5"
  },
  // Mode names
  modes: {
    default: {
      name: "\u666E\u901A",
      icon: "\u26A1"
    },
    yolo: {
      name: "\u6781\u901F",
      icon: "\u{1F680}"
    },
    smart: {
      name: "\u667A\u80FD",
      icon: "\u{1F9E0}"
    },
    plan: {
      name: "\u89C4\u5212",
      icon: "\u{1F4CB}"
    }
  },
  // UI Labels
  ui: {
    send: "\u53D1\u9001",
    thinking: "\u601D\u8003",
    newConversation: "\u65B0\u5BF9\u8BDD",
    today: "\u4ECA\u5929",
    yesterday: "\u6628\u5929",
    thisWeek: "\u672C\u5468",
    older: "\u66F4\u65E9",
    messages: "\u6761\u6D88\u606F",
    noMessages: "0 \u6761\u6D88\u606F",
    noConversations: "\u6682\u65E0\u5BF9\u8BDD",
    noConversationsFound: "\u672A\u627E\u5230\u5BF9\u8BDD",
    searchConversations: "\u641C\u7D22\u5BF9\u8BDD...",
    now: "\u521A\u521A",
    minutesAgo: "{n}\u5206\u949F\u524D",
    hoursAgo: "{n}\u5C0F\u65F6\u524D"
  },
  // Input placeholder
  input: {
    placeholder: "\u5411 iFlow \u63D0\u95EE... (\u4F7F\u7528 @ \u5F15\u7528\u6587\u4EF6, Shift+Enter \u6362\u884C)"
  },
  // Welcome message
  welcome: {
    title: "\u{1F44B} \u6B22\u8FCE\u4F7F\u7528 iFlow!",
    subtitle: "\u60A8\u7684 Obsidian AI \u7F16\u7A0B\u52A9\u624B\u3002",
    helpTitle: "\u6211\u53EF\u4EE5\u5E2E\u52A9\u60A8\uFF1A",
    helpItems: [
      "\u2022 \u9605\u8BFB\u548C\u7F16\u8F91\u7B14\u8BB0",
      "\u2022 \u641C\u7D22\u60A8\u7684\u4ED3\u5E93",
      "\u2022 \u7F16\u5199\u548C\u91CD\u6784\u4EE3\u7801",
      "\u2022 \u56DE\u7B54\u95EE\u9898"
    ],
    hint: "\n\u9009\u62E9\u4E0A\u65B9\u7684\u6A21\u578B\u548C\u6A21\u5F0F\uFF0C\u7136\u540E\u5F00\u59CB\u8F93\u5165\uFF01"
  },
  // Tool calls
  tools: {
    params: "\u53C2\u6570\uFF1A",
    result: "\u7ED3\u679C\uFF1A",
    error: "\u274C \u9519\u8BEF: "
  },
  // Message roles
  roles: {
    user: "\u4F60",
    assistant: "iFlow"
  },
  // Errors
  errors: {
    streamingTimeout: "\u6D41\u5F0F\u4F20\u8F93\u8D85\u65F6",
    connectionFailed: "\u8FDE\u63A5\u5931\u8D25"
  },
  // Settings page
  settings: {
    title: "iFlow for Obsidian \u8BBE\u7F6E",
    port: "iFlow CLI WebSocket \u7AEF\u53E3",
    portDesc: "iFlow CLI \u76D1\u542C\u7684\u7AEF\u53E3\u53F7 (\u9ED8\u8BA4: 8090)",
    timeout: "\u8FDE\u63A5\u8D85\u65F6 (\u6BEB\u79D2)",
    timeoutDesc: "\u8FDE\u63A5 iFlow CLI \u7684\u8D85\u65F6\u65F6\u95F4 (\u9ED8\u8BA4: 60000)",
    autoScroll: "\u542F\u7528\u81EA\u52A8\u6EDA\u52A8",
    autoScrollDesc: "\u5728\u6D41\u5F0F\u54CD\u5E94\u671F\u95F4\u81EA\u52A8\u6EDA\u52A8\u5230\u5E95\u90E8",
    excludedTags: "\u6392\u9664\u6807\u7B7E",
    excludedTagsDesc: "\u5E26\u6709\u8FD9\u4E9B\u6807\u7B7E\u7684\u7B14\u8BB0\u4E0D\u4F1A\u81EA\u52A8\u9644\u52A0\u5230\u5BF9\u8BDD\u4E2D (\u7528\u9017\u53F7\u5206\u9694)",
    language: "\u754C\u9762\u8BED\u8A00",
    languageDesc: "\u9009\u62E9\u63D2\u4EF6\u754C\u9762\u7684\u663E\u793A\u8BED\u8A00",
    languageOptions: {
      "zh-CN": "\u4E2D\u6587\u7B80\u4F53",
      "en-US": "English"
    },
    cliRequirements: "iFlow CLI \u8981\u6C42",
    cliRequirementsDesc: "\u6B64\u63D2\u4EF6\u9700\u8981\u5B89\u88C5\u5E76\u8FD0\u884C iFlow CLI\u3002\u5B89\u88C5\u547D\u4EE4: npm install -g @iflow-ai/iflow-cli@latest",
    connectionStatus: "\u8FDE\u63A5\u72B6\u6001: ",
    connected: "\u2713 \u5DF2\u8FDE\u63A5",
    disconnected: "\u2717 \u672A\u8FDE\u63A5",
    checking: "\u68C0\u6D4B\u4E2D...",
    autoAttachFile: "\u81EA\u52A8\u9644\u52A0\u5F53\u524D\u6587\u4EF6",
    autoAttachFileDesc: "\u5F53\u6253\u5F00\u6587\u4EF6\u65F6\u81EA\u52A8\u5C06\u5176\u4F5C\u4E3A\u4E0A\u4E0B\u6587\u9644\u52A0\u5230\u5BF9\u8BDD\u4E2D"
  },
  // Attachment context
  attachment: {
    removeFile: "\u79FB\u9664\u9644\u4EF6",
    noFileAttached: "\u65E0\u9644\u52A0\u6587\u4EF6",
    dropImageHere: "\u62D6\u653E\u56FE\u7247\u5230\u6B64\u5904",
    pasteImage: "\u6216\u7C98\u8D34\u56FE\u7247 (Ctrl+V)",
    imageTooLarge: "\u56FE\u7247\u5927\u5C0F\u8D85\u8FC7\u9650\u5236 (\u6700\u5927 5MB)",
    unsupportedImageType: "\u4E0D\u652F\u6301\u7684\u56FE\u7247\u683C\u5F0F"
  },
  // Context indicator
  context: {
    file: "\u{1F4C4} ",
    attached: "\u5DF2\u9644\u52A0: "
  }
};

// src/i18n/en-US.ts
var enUS = {
  // Model names
  models: {
    "glm-4.7": "GLM-4.7",
    "glm-5": "GLM-5",
    "deepseek-v3.2-chat": "DeepSeek-V3.2",
    "iFlow-ROME-30BA3B": "iFlow-ROME-30BA3B(Preview)",
    "qwen3-coder-plus": "Qwen3-Coder-Plus",
    "kimi-k2-thinking": "Kimi-K2-Thinking",
    "minimax-m2.5": "MiniMax-M2.5",
    "minimax-m2.1": "MiniMax-M2.1",
    "kimi-k2-0905": "Kimi-K2-0905",
    "kimi-k2.5": "Kimi-K2.5"
  },
  // Mode names
  modes: {
    default: {
      name: "Normal",
      icon: "\u26A1"
    },
    yolo: {
      name: "YOLO",
      icon: "\u{1F680}"
    },
    smart: {
      name: "Smart",
      icon: "\u{1F9E0}"
    },
    plan: {
      name: "Plan",
      icon: "\u{1F4CB}"
    }
  },
  // UI Labels
  ui: {
    send: "Send",
    thinking: "Thinking",
    newConversation: "New Conversation",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    older: "Older",
    messages: "messages",
    noMessages: "0 messages",
    noConversations: "No conversations yet",
    noConversationsFound: "No conversations found",
    searchConversations: "Search conversations...",
    now: "now",
    minutesAgo: "{n}m",
    hoursAgo: "{n}h"
  },
  // Input placeholder
  input: {
    placeholder: "Ask iFlow anything... (Use @ to reference files, Shift+Enter for new line)"
  },
  // Welcome message
  welcome: {
    title: "\u{1F44B} Welcome to iFlow!",
    subtitle: "Your AI-powered coding assistant for Obsidian.",
    helpTitle: "I can help you with:",
    helpItems: [
      "\u2022 Reading and editing your notes",
      "\u2022 Searching your vault",
      "\u2022 Writing and refactoring code",
      "\u2022 Answering questions"
    ],
    hint: "\nSelect a model and mode above, then start typing!"
  },
  // Tool calls
  tools: {
    params: "\u53C2\u6570\uFF1A",
    result: "\u7ED3\u679C\uFF1A",
    error: "\u274C Error: "
  },
  // Message roles
  roles: {
    user: "You",
    assistant: "iFlow"
  },
  // Errors
  errors: {
    streamingTimeout: "Streaming timeout",
    connectionFailed: "Connection failed"
  },
  // Settings page
  settings: {
    title: "iFlow for Obsidian Settings",
    port: "iFlow CLI WebSocket Port",
    portDesc: "The port number that iFlow CLI is listening on (default: 8090)",
    timeout: "Connection Timeout (ms)",
    timeoutDesc: "Timeout for connecting to iFlow CLI (default: 60000)",
    autoScroll: "Enable Auto Scroll",
    autoScrollDesc: "Automatically scroll to bottom during streaming responses",
    excludedTags: "Excluded Tags",
    excludedTagsDesc: "Notes with these tags will not be automatically attached to conversations (comma-separated)",
    language: "Interface Language",
    languageDesc: "Select the display language for the plugin interface",
    languageOptions: {
      "zh-CN": "\u4E2D\u6587\u7B80\u4F53",
      "en-US": "English"
    },
    cliRequirements: "iFlow CLI Requirements",
    cliRequirementsDesc: "This plugin requires iFlow CLI to be installed and running. Install it with: npm install -g @iflow-ai/iflow-cli@latest",
    connectionStatus: "Connection Status: ",
    connected: "\u2713 Connected",
    disconnected: "\u2717 Disconnected",
    checking: "Checking...",
    autoAttachFile: "Auto Attach Current File",
    autoAttachFileDesc: "Automatically attach the current file as context when opening it"
  },
  // Attachment context
  attachment: {
    removeFile: "Remove attachment",
    noFileAttached: "No file attached",
    dropImageHere: "Drop image here",
    pasteImage: "or paste image (Ctrl+V)",
    imageTooLarge: "Image exceeds size limit (max 5MB)",
    unsupportedImageType: "Unsupported image type"
  },
  // Context indicator
  context: {
    file: "\u{1F4C4} ",
    attached: "Attached: "
  }
};

// src/i18n/index.ts
var languages = {
  "zh-CN": zhCN,
  "en-US": enUS,
  "zh": zhCN,
  // alias for zh-CN
  "en": enUS
  // alias for en-US
};
var currentLang = zhCN;
function detectLanguage() {
  var _a;
  if (typeof window !== "undefined" && ((_a = window.obsidian) == null ? void 0 : _a.locale)) {
    return window.obsidian.locale;
  }
  if (typeof navigator !== "undefined") {
    const browserLang = navigator.language || navigator.userLanguage;
    return browserLang || "en-US";
  }
  return "en-US";
}
function initI18n(langCode) {
  const code = langCode || detectLanguage();
  if (languages[code]) {
    currentLang = languages[code];
    return;
  }
  const baseLang = code.split("-")[0];
  if (languages[baseLang]) {
    currentLang = languages[baseLang];
    return;
  }
  currentLang = zhCN;
}
function t() {
  return currentLang;
}
function format(template, vars) {
  return template.replace(/\{(\w+)\}/g, (_, key) => {
    var _a, _b;
    return (_b = (_a = vars[key]) == null ? void 0 : _a.toString()) != null ? _b : `{${key}}`;
  });
}

// src/ui/chat/messageRenderer.ts
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
}
function renderMessage(content) {
  let result = content.replace(/```(\w*)\n([\s\S]*?)```/g, (_match, lang, code) => {
    const langClass = lang ? `language-${lang}` : "";
    return `<pre class="iflow-code-block ${langClass}"><code>${escapeHtml(code.trim())}</code></pre>`;
  });
  result = result.replace(/`([^`]+)`/g, '<code class="iflow-inline-code">$1</code>');
  result = result.replace(/\*\*([^*]+)\*\*/g, '<strong class="iflow-bold">$1</strong>');
  result = result.replace(/\*([^*]+)\*/g, "<em>$1</em>");
  result = result.replace(/^\*\s*(Thinking.+)$/gm, '<div class="iflow-thinking">$1</div>');
  result = result.replace(/^### (.+)$/gm, '<h4 class="iflow-h4">$1</h4>');
  result = result.replace(/^## (.+)$/gm, '<h3 class="iflow-h3">$1</h3>');
  result = result.replace(/^# (.+)$/gm, '<h2 class="iflow-h2">$1</h2>');
  result = result.replace(/^(\s*)[-*]\s+(.+)$/gm, (_match, spaces, text) => {
    const indent = spaces.length;
    return `<li class="iflow-li" style="margin-left: ${indent * 8}px">${text}</li>`;
  });
  result = result.replace(/^(\s*)(\d+)\.\s+(.+)$/gm, (_match, spaces, _num, text) => {
    const indent = spaces.length;
    return `<li class="iflow-li iflow-li-num" style="margin-left: ${indent * 8}px">${text}</li>`;
  });
  result = result.replace(/✅/g, '<span class="iflow-icon iflow-icon-success">\u2705</span>');
  result = result.replace(/❌/g, '<span class="iflow-icon iflow-icon-error">\u274C</span>');
  result = result.replace(/🔄/g, '<span class="iflow-icon iflow-icon-loading">\u{1F504}</span>');
  result = result.replace(/◆/g, '<span class="iflow-icon iflow-icon-diamond">\u25C6</span>');
  result = result.replace(
    /([a-zA-Z0-9_\-/.]+\.(ts|js|tsx|jsx|py|md|json|yaml|yml|css|html))/g,
    '<span class="iflow-file-path">$1</span>'
  );
  result = result.replace(/`([A-Za-z]+\+[A-Za-z+]+)`/g, '<kbd class="iflow-kbd">$1</kbd>');
  result = result.replace(/\n/g, "<br>");
  result = result.replace(/<\/(h[234]|pre|div|li)><br>/g, "</$1>");
  result = result.replace(/<br><(h[234]|pre|div|li)/g, "<$1");
  return result;
}

// src/ui/chat/messageListView.ts
function resolveRoleLabel(role, labels) {
  if (role === "user") return labels.user;
  if (role === "assistant") return labels.assistant;
  return role;
}
var MessageListView = class {
  constructor(container, labels) {
    this.container = container;
    this.labels = labels;
  }
  appendMessage(role, content, id) {
    const messageEl = this.container.createDiv({
      cls: `iflow-message iflow-message-${role}`
    });
    messageEl.dataset.id = id;
    messageEl.createDiv({ cls: "iflow-message-role", text: resolveRoleLabel(role, this.labels) });
    const contentEl = messageEl.createDiv({ cls: "iflow-message-content" });
    contentEl.innerHTML = renderMessage(content);
  }
  updateMessage(id, content) {
    const messageEl = this.container.querySelector(`[data-id="${id}"]`);
    if (!messageEl) return;
    const contentEl = messageEl.querySelector(".iflow-message-content");
    if (!contentEl) return;
    contentEl.innerHTML = renderMessage(content);
  }
  showLoading(messageId, text) {
    const contentEl = this.getMessageContentElement(messageId);
    if (!contentEl) return;
    contentEl.innerHTML = `
			<div class="iflow-loading">
				<div class="iflow-loading-dots">
					<span></span>
					<span></span>
					<span></span>
				</div>
				<span class="iflow-loading-text">${text}</span>
			</div>
		`;
  }
  hideLoading(messageId) {
    const messageEl = this.container.querySelector(`[data-id="${messageId}"]`);
    if (!messageEl) return;
    const loadingEl = messageEl.querySelector(".iflow-loading");
    if (loadingEl) {
      loadingEl.remove();
    }
  }
  getMessageContentElement(messageId) {
    const messageEl = this.container.querySelector(`[data-id="${messageId}"]`);
    if (!messageEl) return null;
    return messageEl.querySelector(".iflow-message-content");
  }
  scrollToBottom() {
    requestAnimationFrame(() => {
      this.container.scrollTop = this.container.scrollHeight;
    });
  }
  loadConversation(messages) {
    this.container.empty();
    for (const msg of messages) {
      this.appendMessage(msg.role, msg.content, msg.id);
    }
  }
};

// src/ui/chat/toolCallView.ts
function formatToolStatusIcon(status) {
  if (status === "completed") return "\u2705";
  if (status === "error") return "\u274C";
  return "\u{1F504}";
}
var ToolCallView = class {
  constructor(labels) {
    this.labels = labels;
  }
  showOrUpdate(messageContainer, tool) {
    let toolContainer = messageContainer.querySelector(`.iflow-tool-call[data-tool-id="${tool.id}"]`);
    if (!toolContainer) {
      toolContainer = messageContainer.createDiv({
        cls: `iflow-tool-call iflow-tool-status-${tool.status || "running"}`
      });
      toolContainer.dataset.toolId = tool.id;
      const header = toolContainer.createDiv({ cls: "iflow-tool-header" });
      header.createSpan({ cls: "iflow-tool-icon", text: formatToolStatusIcon(tool.status) });
      header.createSpan({ cls: "iflow-tool-name", text: tool.name });
      const details = toolContainer.createDiv({ cls: "iflow-tool-details" });
      if (tool.input && Object.keys(tool.input).length > 0) {
        details.createDiv({ cls: "iflow-tool-section-title", text: this.labels.params });
        const inputPre = details.createEl("pre", { cls: "iflow-tool-input" });
        inputPre.createEl("code", { text: JSON.stringify(tool.input, null, 2) });
      }
      return;
    }
    toolContainer.className = `iflow-tool-call iflow-tool-status-${tool.status || "running"}`;
    const iconEl = toolContainer.querySelector(".iflow-tool-icon");
    if (iconEl) {
      iconEl.textContent = formatToolStatusIcon(tool.status);
    }
    if (tool.status === "completed" && tool.result) {
      let resultEl = toolContainer.querySelector(".iflow-tool-result");
      if (!resultEl) {
        const details = toolContainer.querySelector(".iflow-tool-details");
        if (details) {
          details.createDiv({ cls: "iflow-tool-section-title", text: this.labels.result });
          resultEl = details.createEl("pre", { cls: "iflow-tool-result" });
          const resultText = typeof tool.result === "string" ? tool.result : JSON.stringify(tool.result, null, 2);
          resultEl.createEl("code", { text: resultText });
        }
      }
    }
    if (tool.status === "error" && tool.error) {
      let errorEl = toolContainer.querySelector(".iflow-tool-error");
      if (!errorEl) {
        const details = toolContainer.querySelector(".iflow-tool-details");
        if (details) {
          errorEl = details.createDiv({ cls: "iflow-tool-error" });
          errorEl.createSpan({ text: `${this.labels.errorPrefix}${tool.error}` });
        }
      }
    }
  }
};

// src/ui/chat/imageAttachmentView.ts
var MAX_IMAGE_SIZE = 5 * 1024 * 1024;
var IMAGE_EXTENSIONS = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".gif": "image/gif",
  ".webp": "image/webp"
};
function getImageMediaType(filename) {
  var _a;
  const dotIndex = filename.lastIndexOf(".");
  if (dotIndex < 0) {
    return null;
  }
  const ext = filename.toLowerCase().substring(dotIndex);
  return (_a = IMAGE_EXTENSIONS[ext]) != null ? _a : null;
}
function isSupportedImageFile(file) {
  return file.type.startsWith("image/") && getImageMediaType(file.name) !== null;
}
function generateImageAttachmentId(now = Date.now(), randomValue = Math.random()) {
  const randomPart = Math.floor(randomValue * 36).toString(36);
  return `img-${now}-${randomPart}`;
}
function truncateImageName(name, maxLen) {
  if (name.length <= maxLen) {
    return name;
  }
  const dotIndex = name.lastIndexOf(".");
  const ext = dotIndex >= 0 ? name.substring(dotIndex) : "";
  const base = dotIndex >= 0 ? name.substring(0, dotIndex) : name;
  const availableLength = Math.max(1, maxLen - ext.length - 3);
  return `${base.substring(0, availableLength)}...${ext}`;
}
function formatImageSize(bytes) {
  if (bytes < 1024) {
    return `${bytes} B`;
  }
  if (bytes < 1024 * 1024) {
    return `${(bytes / 1024).toFixed(1)} KB`;
  }
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// src/domain/conversation/storageQuotaPolicy.ts
var MAX_STORAGE_BYTES = 4 * 1024 * 1024;
function cleanupOldConversations(conversations, currentConversationId, keepCount = 50) {
  var _a;
  const sorted = [...conversations].sort((a, b) => b.updatedAt - a.updatedAt);
  const kept = sorted.slice(0, keepCount);
  const removedCount = Math.max(0, conversations.length - kept.length);
  let nextCurrentConversationId = currentConversationId;
  if (nextCurrentConversationId) {
    const stillExists = kept.find((conversation) => conversation.id === nextCurrentConversationId);
    if (!stillExists) {
      nextCurrentConversationId = ((_a = kept[0]) == null ? void 0 : _a.id) || null;
    }
  }
  return {
    conversations: kept,
    currentConversationId: nextCurrentConversationId,
    removedCount
  };
}

// src/domain/conversation/conversationService.ts
var ConversationService = class {
  constructor(repository) {
    this.repository = repository;
  }
  getState() {
    return this.repository.getState();
  }
  getCurrentConversation() {
    const state = this.repository.getState();
    if (!state.currentConversationId) {
      return null;
    }
    return state.conversations.find((c) => c.id === state.currentConversationId) || null;
  }
  newConversation(defaultModel = "glm-4.7", defaultMode = "default", defaultThink = false) {
    var _a, _b, _c;
    const state = this.repository.getState();
    const current = this.getCurrentConversation();
    const conversation = {
      id: `conv-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`,
      title: "New Conversation",
      messages: [],
      mode: (_a = current == null ? void 0 : current.mode) != null ? _a : defaultMode,
      think: (_b = current == null ? void 0 : current.think) != null ? _b : defaultThink,
      model: (_c = current == null ? void 0 : current.model) != null ? _c : defaultModel,
      createdAt: Date.now(),
      updatedAt: Date.now()
    };
    this.repository.setState({
      currentConversationId: conversation.id,
      conversations: [conversation, ...state.conversations]
    });
    return conversation;
  }
  switchConversation(conversationId) {
    const state = this.repository.getState();
    if (!state.conversations.find((c) => c.id === conversationId)) {
      return;
    }
    this.repository.setState({ ...state, currentConversationId: conversationId });
  }
  deleteConversation(conversationId) {
    const state = this.repository.getState();
    const conversations = state.conversations.filter((c) => c.id !== conversationId);
    let currentConversationId = state.currentConversationId;
    if (currentConversationId === conversationId) {
      currentConversationId = conversations.length > 0 ? conversations[0].id : null;
    }
    this.repository.setState({ currentConversationId, conversations });
  }
  updateConversationSettings(conversationId, settings) {
    const state = this.repository.getState();
    const conversations = state.conversations.map(
      (c) => c.id === conversationId ? { ...c, ...settings, updatedAt: Date.now() } : c
    );
    this.repository.setState({ ...state, conversations });
  }
  getConversationMessages(conversationId) {
    var _a;
    const state = this.repository.getState();
    const conversation = state.conversations.find((c) => c.id === conversationId);
    return (_a = conversation == null ? void 0 : conversation.messages) != null ? _a : [];
  }
  appendUserMessage(conversationId, content) {
    const state = this.repository.getState();
    const message = {
      id: `msg-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`,
      role: "user",
      content,
      timestamp: Date.now()
    };
    const conversations = state.conversations.map((conversation) => {
      if (conversation.id !== conversationId) {
        return conversation;
      }
      const title = conversation.title === "New Conversation" ? this.generateTitle(content) : conversation.title;
      return {
        ...conversation,
        title,
        messages: [...conversation.messages, message],
        updatedAt: Date.now()
      };
    });
    const cleanupResult = cleanupOldConversations(conversations, state.currentConversationId, 50);
    this.repository.setState({
      currentConversationId: cleanupResult.currentConversationId,
      conversations: cleanupResult.conversations
    });
    return message;
  }
  appendAssistantMessage(conversationId, content) {
    const state = this.repository.getState();
    const message = {
      id: `msg-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`,
      role: "assistant",
      content,
      timestamp: Date.now()
    };
    const conversations = state.conversations.map((conversation) => {
      if (conversation.id !== conversationId) {
        return conversation;
      }
      return {
        ...conversation,
        messages: [...conversation.messages, message],
        updatedAt: Date.now()
      };
    });
    this.repository.setState({ ...state, conversations });
    return message;
  }
  subscribe(listener) {
    return this.repository.subscribe(listener);
  }
  generateTitle(firstMessage) {
    const trimmed = firstMessage.trim();
    return trimmed.length > 50 ? `${trimmed.substring(0, 47)}...` : trimmed;
  }
};

// src/domain/conversation/conversationRepository.ts
var STORAGE_VERSION = 1;
var LocalStorageConversationRepository = class {
  constructor(vaultPath, storage = localStorage) {
    this.storage = storage;
    this.listeners = /* @__PURE__ */ new Set();
    this.storageKey = `iflow-conversations-${this.hashVaultPath(vaultPath)}`;
    this.state = this.load();
  }
  getState() {
    return {
      currentConversationId: this.state.currentConversationId,
      conversations: [...this.state.conversations]
    };
  }
  setState(state) {
    this.state = {
      currentConversationId: state.currentConversationId,
      conversations: [...state.conversations]
    };
    this.save();
    this.listeners.forEach((listener) => listener());
  }
  subscribe(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }
  load() {
    var _a, _b;
    try {
      const data = this.storage.getItem(this.storageKey);
      if (data) {
        const parsed = JSON.parse(data);
        return {
          currentConversationId: (_a = parsed.currentConversationId) != null ? _a : null,
          conversations: (_b = parsed.conversations) != null ? _b : []
        };
      }
    } catch (error) {
      console.error("[ConversationRepository] Failed to load:", error);
    }
    return { currentConversationId: null, conversations: [] };
  }
  save() {
    try {
      const persisted = {
        ...this.state,
        version: STORAGE_VERSION,
        updatedAt: Date.now()
      };
      this.storage.setItem(this.storageKey, JSON.stringify(persisted));
    } catch (error) {
      console.error("[ConversationRepository] Failed to save:", error);
    }
  }
  hashVaultPath(path2) {
    let hash = 0;
    for (let i = 0; i < path2.length; i++) {
      const char = path2.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash;
    }
    return Math.abs(hash).toString(36);
  }
};

// src/chatView.ts
var VIEW_TYPE_IFLOW_CHAT = "iflow-chat-view";
var IFlowChatView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin, iflowService) {
    super(leaf);
    this.messages = [];
    this.currentMessage = "";
    this.isStreaming = false;
    // Available models and modes from iFlow CLI
    this.availableModels = [];
    this.availableModes = [];
    // Conversation management
    this.currentConversationId = null;
    this.conversationTitleEl = null;
    this.isLoadingMessages = false;
    // 防止在加载期间重复加载
    this.showConversationPanel = false;
    // Panel visibility state
    // File attachment
    this.currentFile = null;
    this.attachedFile = null;
    // Manually attached file
    // Image attachments
    this.attachedImages = /* @__PURE__ */ new Map();
    this.imagePreviewEl = null;
    this.dropOverlay = null;
    this.streamingTimeout = null;
    this.plugin = plugin;
    this.iflowService = iflowService;
    this.currentModel = plugin.settings.lastUsedModel || "glm-4.7";
    this.currentMode = plugin.settings.lastUsedMode || "default";
    this.thinkingEnabled = plugin.settings.lastUsedThinking || false;
    initI18n();
    const vaultPath = this.plugin.getVaultPath();
    const repository = new LocalStorageConversationRepository(vaultPath);
    this.conversationService = new ConversationService(repository);
    this.conversationService.subscribe(() => this.onConversationChange());
  }
  getViewType() {
    return VIEW_TYPE_IFLOW_CHAT;
  }
  getDisplayText() {
    return "iFlow Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("iflow-chat-container");
    const chatContainer = container.createDiv({ cls: "iflow-chat" });
    const topBar = chatContainer.createDiv({ cls: "iflow-top-bar" });
    this.createConversationSelector(topBar);
    const controlBar = chatContainer.createDiv({ cls: "iflow-control-bar" });
    const modelSelector = this.createModelSelector(controlBar);
    const rightControls = controlBar.createDiv({ cls: "iflow-control-right" });
    const modeSelector = this.createModeSelector(rightControls);
    const thinkingToggle = this.createThinkingToggle(rightControls);
    const contextArea = chatContainer.createDiv({ cls: "iflow-context-area" });
    this.imagePreviewEl = contextArea.createDiv({ cls: "iflow-image-preview" });
    this.imagePreviewEl.style.display = "none";
    const contextIndicator = contextArea.createDiv({ cls: "iflow-context-indicator" });
    this.contextIndicator = contextIndicator;
    const messagesContainer = chatContainer.createDiv({ cls: "iflow-messages" });
    this.messagesContainer = messagesContainer;
    this.messageListView = new MessageListView(messagesContainer, {
      user: t().roles.user,
      assistant: t().roles.assistant
    });
    this.toolCallView = new ToolCallView({
      params: t().tools.params,
      result: t().tools.result,
      errorPrefix: t().tools.error
    });
    const inputContainer = chatContainer.createDiv({ cls: "iflow-input-container" });
    const inputWrapper = inputContainer.createDiv({ cls: "iflow-input-wrapper" });
    const textarea = inputWrapper.createEl("textarea", {
      cls: "iflow-input",
      attr: { placeholder: t().input.placeholder }
    });
    this.textarea = textarea;
    const sendButton = inputWrapper.createEl("button", {
      cls: "iflow-send-button",
      text: t().ui.send
    });
    sendButton.onclick = () => this.sendMessage();
    textarea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.setupImageDropAndPaste(inputWrapper);
    this.updateContext();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.updateContext())
    );
    this.initializeConversation();
  }
  initializeConversation() {
    const state = this.conversationService.getState();
    this.currentConversationId = state.currentConversationId;
    if (this.currentConversationId) {
      this.loadMessagesFromConversation();
    } else {
      this.createNewConversation();
    }
  }
  async onClose() {
  }
  updateContext() {
    const activeFile = this.plugin.getActiveFile();
    if (this.plugin.settings.autoAttachFile) {
      this.currentFile = activeFile;
    } else {
      this.currentFile = null;
    }
    this.renderContextIndicator();
  }
  renderContextIndicator() {
    this.contextIndicator.empty();
    const fileToShow = this.attachedFile || this.currentFile;
    if (fileToShow) {
      const fileSpan = this.contextIndicator.createSpan({ cls: "iflow-context-file" });
      fileSpan.textContent = `${t().context.attached}${fileToShow.path}`;
      const removeBtn = this.contextIndicator.createSpan({ cls: "iflow-context-remove", text: "\xD7" });
      removeBtn.onclick = () => {
        this.attachedFile = null;
        this.currentFile = null;
        this.renderContextIndicator();
      };
    }
  }
  // ============================================
  // Image Handling
  // ============================================
  setupImageDropAndPaste(inputWrapper) {
    this.dropOverlay = inputWrapper.createDiv({ cls: "iflow-drop-overlay" });
    const dropContent = this.dropOverlay.createDiv({ cls: "iflow-drop-content" });
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("viewBox", "0 0 24 24");
    svg.setAttribute("width", "32");
    svg.setAttribute("height", "32");
    svg.setAttribute("fill", "none");
    svg.setAttribute("stroke", "currentColor");
    svg.setAttribute("stroke-width", "2");
    svg.innerHTML = '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/>';
    dropContent.appendChild(svg);
    dropContent.createSpan({ text: t().attachment.dropImageHere });
    inputWrapper.addEventListener("dragenter", (e) => this.handleDragEnter(e));
    inputWrapper.addEventListener("dragover", (e) => this.handleDragOver(e));
    inputWrapper.addEventListener("dragleave", (e) => this.handleDragLeave(e));
    inputWrapper.addEventListener("drop", (e) => this.handleDrop(e));
    this.textarea.addEventListener("paste", async (e) => {
      var _a;
      const items = (_a = e.clipboardData) == null ? void 0 : _a.items;
      if (!items) return;
      for (let i = 0; i < items.length; i++) {
        const item = items[i];
        if (item.type.startsWith("image/")) {
          e.preventDefault();
          const file = item.getAsFile();
          if (file) {
            await this.addImageFromFile(file, "paste");
          }
          return;
        }
      }
    });
  }
  handleDragEnter(e) {
    var _a, _b;
    e.preventDefault();
    e.stopPropagation();
    if ((_a = e.dataTransfer) == null ? void 0 : _a.types.includes("Files")) {
      (_b = this.dropOverlay) == null ? void 0 : _b.addClass("visible");
    }
  }
  handleDragOver(e) {
    e.preventDefault();
    e.stopPropagation();
  }
  handleDragLeave(e) {
    var _a, _b;
    e.preventDefault();
    e.stopPropagation();
    const inputWrapper = this.containerEl.querySelector(".iflow-input-wrapper");
    if (!inputWrapper) {
      (_a = this.dropOverlay) == null ? void 0 : _a.removeClass("visible");
      return;
    }
    const rect = inputWrapper.getBoundingClientRect();
    if (e.clientX <= rect.left || e.clientX >= rect.right || e.clientY <= rect.top || e.clientY >= rect.bottom) {
      (_b = this.dropOverlay) == null ? void 0 : _b.removeClass("visible");
    }
  }
  async handleDrop(e) {
    var _a, _b;
    e.preventDefault();
    e.stopPropagation();
    (_a = this.dropOverlay) == null ? void 0 : _a.removeClass("visible");
    const files = (_b = e.dataTransfer) == null ? void 0 : _b.files;
    if (!files) return;
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      if (this.isImageFile(file)) {
        await this.addImageFromFile(file, "drop");
      }
    }
  }
  isImageFile(file) {
    return isSupportedImageFile(file);
  }
  getMediaType(filename) {
    return getImageMediaType(filename);
  }
  async addImageFromFile(file, source) {
    if (file.size > MAX_IMAGE_SIZE) {
      new import_obsidian2.Notice(t().attachment.imageTooLarge);
      return false;
    }
    const mediaType = this.getMediaType(file.name) || file.type;
    if (!mediaType) {
      new import_obsidian2.Notice(t().attachment.unsupportedImageType);
      return false;
    }
    try {
      const base64 = await this.fileToBase64(file);
      const attachment = {
        id: this.generateImageId(),
        name: file.name || `image-${Date.now()}.${mediaType.split("/")[1]}`,
        mediaType,
        data: base64,
        size: file.size,
        source
      };
      this.attachedImages.set(attachment.id, attachment);
      this.updateImagePreview();
      return true;
    } catch (error) {
      console.error("[iFlow] Failed to attach image:", error);
      return false;
    }
  }
  async fileToBase64(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result;
        const base64 = result.split(",")[1];
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  }
  generateImageId() {
    return generateImageAttachmentId();
  }
  updateImagePreview() {
    if (!this.imagePreviewEl) return;
    this.imagePreviewEl.empty();
    if (this.attachedImages.size === 0) {
      this.imagePreviewEl.style.display = "none";
      return;
    }
    this.imagePreviewEl.style.display = "flex";
    for (const [id, image] of this.attachedImages) {
      this.renderImagePreview(id, image);
    }
  }
  renderImagePreview(id, image) {
    const chip = this.imagePreviewEl.createDiv({ cls: "iflow-image-chip" });
    const thumb = chip.createDiv({ cls: "iflow-image-thumb" });
    thumb.createEl("img", {
      attr: {
        src: `data:${image.mediaType};base64,${image.data}`,
        alt: image.name
      }
    });
    const info = chip.createDiv({ cls: "iflow-image-info" });
    info.createSpan({ cls: "iflow-image-name", text: this.truncateName(image.name, 15) });
    info.createSpan({ cls: "iflow-image-size", text: this.formatSize(image.size) });
    const remove = chip.createSpan({ cls: "iflow-image-remove", text: "\xD7" });
    remove.onclick = () => {
      this.attachedImages.delete(id);
      this.updateImagePreview();
    };
    thumb.onclick = () => this.showFullImage(image);
  }
  showFullImage(image) {
    const overlay = document.body.createDiv({ cls: "iflow-image-modal-overlay" });
    const modal = overlay.createDiv({ cls: "iflow-image-modal" });
    modal.createEl("img", {
      attr: {
        src: `data:${image.mediaType};base64,${image.data}`,
        alt: image.name
      }
    });
    const closeBtn = modal.createDiv({ cls: "iflow-image-modal-close", text: "\xD7" });
    const handleEsc = (e) => {
      if (e.key === "Escape") close();
    };
    const close = () => {
      document.removeEventListener("keydown", handleEsc);
      overlay.remove();
    };
    closeBtn.onclick = close;
    overlay.onclick = (e) => {
      if (e.target === overlay) close();
    };
    document.addEventListener("keydown", handleEsc);
  }
  truncateName(name, maxLen) {
    return truncateImageName(name, maxLen);
  }
  formatSize(bytes) {
    return formatImageSize(bytes);
  }
  async sendMessage() {
    var _a;
    const content = this.textarea.value.trim();
    console.log("[iFlow Chat] sendMessage called", {
      content,
      isStreaming: this.isStreaming,
      currentConversationId: this.currentConversationId
    });
    if (!content) {
      console.log("[iFlow Chat] Message blocked: empty content");
      return;
    }
    if (this.isStreaming) {
      console.warn("[iFlow Chat] Force reset: was stuck in streaming state");
      this.isStreaming = false;
      if (this.streamingTimeout) {
        clearTimeout(this.streamingTimeout);
        this.streamingTimeout = null;
      }
    }
    if (!this.currentConversationId) {
      console.log("[iFlow Chat] Creating new conversation");
      this.createNewConversation();
    }
    const activeFile = this.plugin.getActiveFile();
    let fileContent = "";
    let selection = "";
    if (activeFile) {
      const metadata = this.app.metadataCache.getFileCache(activeFile);
      const tags = ((_a = metadata == null ? void 0 : metadata.tags) == null ? void 0 : _a.map((t2) => t2.tag)) || [];
      const hasExcludedTag = this.plugin.settings.excludedTags.some(
        (tag) => tags.includes(tag)
      );
      if (!hasExcludedTag) {
        fileContent = await this.app.vault.read(activeFile);
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
        if (activeView == null ? void 0 : activeView.editor) {
          selection = activeView.editor.getSelection();
        }
      }
    }
    const userMsgId = this.addMessage("user", content);
    this.textarea.value = "";
    this.attachedImages.clear();
    this.updateImagePreview();
    if (this.currentConversationId) {
      this.conversationService.appendUserMessage(this.currentConversationId, content);
    }
    const assistantMsgId = this.addMessage("assistant", "");
    this.currentMessage = "";
    this.isStreaming = true;
    this.showLoadingAnimation(assistantMsgId);
    console.log("[iFlow Chat] Starting streaming", {
      userMsgId,
      assistantMsgId,
      isStreaming: this.isStreaming
    });
    this.streamingTimeout = setTimeout(() => {
      console.warn("[iFlow Chat] Streaming timeout: forcing reset");
      this.isStreaming = false;
      this.streamingTimeout = null;
    }, 6e4);
    if (this.plugin.settings.enableAutoScroll) {
      this.scrollToBottom();
    }
    const cleanup = () => {
      if (this.streamingTimeout) {
        clearTimeout(this.streamingTimeout);
        this.streamingTimeout = null;
      }
      this.isStreaming = false;
      console.log("[iFlow Chat] Cleanup: streaming state reset");
    };
    try {
      await this.iflowService.sendMessage({
        content,
        filePath: activeFile == null ? void 0 : activeFile.path,
        fileContent,
        selection,
        model: this.currentModel,
        mode: this.currentMode,
        thinkingEnabled: this.thinkingEnabled,
        onChunk: (chunk) => {
          if (!this.currentMessage) {
            this.hideLoadingAnimation(assistantMsgId);
          }
          this.currentMessage += chunk;
          this.updateMessage(assistantMsgId, this.currentMessage);
          if (this.plugin.settings.enableAutoScroll) {
            this.scrollToBottom();
          }
        },
        onTool: (tool) => {
          console.log("[iFlow Chat] Tool call:", tool);
          this.showOrUpdateToolCall(assistantMsgId, tool);
          if (this.plugin.settings.enableAutoScroll) {
            this.scrollToBottom();
          }
        },
        onEnd: () => {
          console.log("[iFlow Chat] onEnd called, setting isStreaming = false");
          cleanup();
          if (this.currentConversationId && this.currentMessage) {
            this.conversationService.appendAssistantMessage(
              this.currentConversationId,
              this.currentMessage
            );
          }
          this.updateConversationUI();
        },
        onError: (error) => {
          console.log("[iFlow Chat] onError called", error);
          cleanup();
          this.updateMessage(assistantMsgId, `Error: ${error}`);
        }
      });
    } catch (error) {
      console.log("[iFlow Chat] Exception in sendMessage", error);
      cleanup();
      this.updateMessage(assistantMsgId, `Error: ${error.message}`);
    }
  }
  addMessage(role, content) {
    const id = Date.now().toString();
    this.messages.push({ role, content, id });
    this.messageListView.appendMessage(role, content, id);
    return id;
  }
  updateMessage(id, content) {
    this.messageListView.updateMessage(id, content);
  }
  showLoadingAnimation(messageId) {
    this.messageListView.showLoading(messageId, "\u601D\u8003\u4E2D...");
  }
  hideLoadingAnimation(messageId) {
    this.messageListView.hideLoading(messageId);
  }
  showOrUpdateToolCall(messageId, tool) {
    const contentEl = this.messageListView.getMessageContentElement(messageId);
    if (!contentEl) return;
    this.toolCallView.showOrUpdate(contentEl, tool);
  }
  scrollToBottom() {
    this.messageListView.scrollToBottom();
  }
  // ============================================
  // UI Component Creators
  // ============================================
  addWelcomeMessage() {
    const greeting = this.getDynamicGreeting();
    this.messagesContainer.createDiv({
      cls: "iflow-welcome"
    }, (el) => {
      const greetingEl = el.createDiv({ cls: "iflow-welcome-greeting" });
      greetingEl.createEl("span", { cls: "iflow-welcome-emoji", text: greeting.emoji });
      greetingEl.createEl("span", { cls: "iflow-welcome-text", text: greeting.text });
      el.createEl("p", { cls: "iflow-welcome-subtitle", text: greeting.subtitle });
    });
  }
  getDynamicGreeting() {
    const now = /* @__PURE__ */ new Date();
    const hour = now.getHours();
    const dayOfWeek = now.getDay();
    if (dayOfWeek === 5) {
      return {
        emoji: "\u{1F389}",
        text: "\u5468\u4E94\u5FEB\u4E50\uFF01",
        subtitle: "\u5468\u672B\u5FEB\u5230\u4E86\uFF0C\u4ECA\u5929\u60F3\u5B8C\u6210\u4EC0\u4E48\uFF1F"
      };
    }
    if (dayOfWeek === 0) {
      return {
        emoji: "\u2600\uFE0F",
        text: "\u5468\u65E5\u6109\u5FEB\uFF01",
        subtitle: "\u4EAB\u53D7\u4F11\u606F\u65F6\u5149\uFF0C\u6709\u9700\u8981\u968F\u65F6\u627E\u6211"
      };
    }
    if (dayOfWeek === 6) {
      return {
        emoji: "\u{1F31F}",
        text: "\u5468\u516D\u597D\uFF01",
        subtitle: "\u5468\u672B\u6109\u5FEB\uFF0C\u4ECA\u5929\u60F3\u505A\u70B9\u4EC0\u4E48\uFF1F"
      };
    }
    if (hour >= 5 && hour < 9) {
      return {
        emoji: "\u{1F305}",
        text: "\u65E9\u5B89\uFF01",
        subtitle: "\u65B0\u7684\u4E00\u5929\u5F00\u59CB\u4E86\uFF0C\u51C6\u5907\u597D\u4E86\u5417\uFF1F"
      };
    }
    if (hour >= 9 && hour < 12) {
      return {
        emoji: "\u2615",
        text: "\u4E0A\u5348\u597D\uFF01",
        subtitle: "\u795D\u4F60\u4ECA\u5929\u5DE5\u4F5C\u6548\u7387\u6EE1\u6EE1"
      };
    }
    if (hour >= 12 && hour < 14) {
      return {
        emoji: "\u{1F37D}\uFE0F",
        text: "\u4E2D\u5348\u597D\uFF01",
        subtitle: "\u8BB0\u5F97\u5403\u5348\u996D\uFF0C\u4E0B\u5348\u7EE7\u7EED\u52A0\u6CB9"
      };
    }
    if (hour >= 14 && hour < 18) {
      return {
        emoji: "\u{1F4AA}",
        text: "\u4E0B\u5348\u597D\uFF01",
        subtitle: "\u6709\u4EC0\u4E48\u6211\u53EF\u4EE5\u5E2E\u4F60\u7684\uFF1F"
      };
    }
    if (hour >= 18 && hour < 22) {
      return {
        emoji: "\u{1F319}",
        text: "\u665A\u4E0A\u597D\uFF01",
        subtitle: "\u4ECA\u5929\u8F9B\u82E6\u4E86\uFF0C\u8FD8\u6709\u4EC0\u4E48\u8981\u5904\u7406\u7684\u5417\uFF1F"
      };
    }
    return {
      emoji: "\u{1F989}",
      text: "\u591C\u6DF1\u4E86",
      subtitle: "\u6CE8\u610F\u4F11\u606F\uFF0C\u71AC\u591C\u4F24\u8EAB\u4F53\u54E6"
    };
  }
  createModelSelector(container) {
    const selector = container.createDiv({ cls: "iflow-model-selector" });
    const defaultModels = [
      { id: "glm-4.7", name: t().models["glm-4.7"] },
      { id: "glm-5", name: t().models["glm-5"] },
      { id: "deepseek-v3.2-chat", name: t().models["deepseek-v3.2-chat"] },
      { id: "iFlow-ROME-30BA3B", name: t().models["iFlow-ROME-30BA3B"] },
      { id: "qwen3-coder-plus", name: t().models["qwen3-coder-plus"] },
      { id: "kimi-k2-thinking", name: t().models["kimi-k2-thinking"] },
      { id: "minimax-m2.5", name: t().models["minimax-m2.5"] },
      { id: "minimax-m2.1", name: t().models["minimax-m2.1"] },
      { id: "kimi-k2-0905", name: t().models["kimi-k2-0905"] },
      { id: "kimi-k2.5", name: t().models["kimi-k2.5"] }
    ];
    this.availableModels = defaultModels;
    const btn = selector.createEl("button", {
      cls: "iflow-model-btn ready"
    });
    const currentModelObj = defaultModels.find((m) => m.id === this.currentModel) || defaultModels[0];
    const label = btn.createSpan({ cls: "iflow-model-label", text: currentModelObj.name });
    const chevron = btn.createDiv({ cls: "iflow-model-chevron" });
    chevron.innerHTML = `
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<polyline points="6 9 12 15 18 9"></polyline>
			</svg>
		`;
    const dropdown = selector.createDiv({ cls: "iflow-model-dropdown" });
    this.availableModels.forEach((model) => {
      dropdown.createDiv({
        cls: `iflow-model-option ${model.id === this.currentModel ? "selected" : ""}`,
        text: model.name
      }, (el) => {
        el.onclick = async (e) => {
          e.stopPropagation();
          this.currentModel = model.id;
          label.textContent = model.name;
          dropdown.querySelectorAll(".iflow-model-option").forEach((opt) => {
            opt.removeClass("selected");
          });
          el.addClass("selected");
          this.plugin.settings.lastUsedModel = model.id;
          await this.plugin.saveSettings();
          selector.removeClass("open");
        };
      });
    });
    btn.onclick = (e) => {
      e.stopPropagation();
      document.querySelectorAll(".iflow-model-selector.open, .iflow-mode-selector.open").forEach((el) => {
        el.removeClass("open");
      });
      selector.toggleClass("open", !selector.hasClass("open"));
    };
    const closeHandler = (e) => {
      if (!selector.contains(e.target)) {
        selector.removeClass("open");
      }
    };
    document.addEventListener("click", closeHandler);
    return selector;
  }
  createModeSelector(container) {
    const selector = container.createDiv({ cls: "iflow-mode-selector" });
    const modes = [
      { id: "default", name: t().modes.default.name, icon: t().modes.default.icon },
      { id: "yolo", name: t().modes.yolo.name, icon: t().modes.yolo.icon },
      { id: "smart", name: t().modes.smart.name, icon: t().modes.smart.icon },
      { id: "plan", name: t().modes.plan.name, icon: t().modes.plan.icon }
    ];
    this.availableModes = modes;
    const btn = selector.createEl("button", {
      cls: "iflow-mode-btn"
    });
    const currentMode = modes.find((m) => m.id === this.currentMode);
    const icon = btn.createSpan({ cls: "iflow-mode-icon", text: (currentMode == null ? void 0 : currentMode.icon) || t().modes.default.icon });
    const label = btn.createSpan({ cls: "iflow-mode-label", text: (currentMode == null ? void 0 : currentMode.name) || t().modes.default.name });
    const chevron = btn.createDiv({ cls: "iflow-mode-chevron" });
    chevron.innerHTML = `
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<polyline points="6 9 12 15 18 9"></polyline>
			</svg>
		`;
    const dropdown = selector.createDiv({ cls: "iflow-mode-dropdown" });
    modes.forEach((mode) => {
      dropdown.createDiv({
        cls: `iflow-mode-option ${mode.id === this.currentMode ? "selected" : ""}`,
        attr: { "data-mode": mode.id }
      }, (el) => {
        const optIcon = el.createSpan({ cls: "iflow-mode-icon", text: mode.icon });
        const optLabel = el.createSpan({ text: mode.name });
        el.onclick = async (e) => {
          e.stopPropagation();
          this.currentMode = mode.id;
          icon.textContent = mode.icon;
          label.textContent = mode.name;
          dropdown.querySelectorAll(".iflow-mode-option").forEach((opt) => {
            opt.removeClass("selected");
          });
          el.addClass("selected");
          this.plugin.settings.lastUsedMode = mode.id;
          await this.plugin.saveSettings();
          selector.removeClass("open");
        };
      });
    });
    btn.onclick = (e) => {
      e.stopPropagation();
      document.querySelectorAll(".iflow-model-selector.open, .iflow-mode-selector.open").forEach((el) => {
        el.removeClass("open");
      });
      selector.toggleClass("open", !selector.hasClass("open"));
    };
    const closeHandler = (e) => {
      if (!selector.contains(e.target)) {
        selector.removeClass("open");
      }
    };
    document.addEventListener("click", closeHandler);
    return selector;
  }
  createThinkingToggle(container) {
    const toggle = container.createEl("button", {
      cls: "iflow-thinking-toggle"
    });
    if (this.thinkingEnabled) {
      toggle.addClass("active");
    }
    const icon = toggle.createSpan({ cls: "iflow-thinking-icon", text: "\u{1F9E0}" });
    const label = toggle.createSpan({ text: t().ui.thinking });
    toggle.onclick = async () => {
      this.thinkingEnabled = !this.thinkingEnabled;
      toggle.toggleClass("active", this.thinkingEnabled);
      this.plugin.settings.lastUsedThinking = this.thinkingEnabled;
      await this.plugin.saveSettings();
    };
    return toggle;
  }
  // ============================================
  // Conversation Management
  // ============================================
  createConversationSelector(container) {
    const selector = container.createDiv({ cls: "iflow-conversation-selector" });
    const trigger = selector.createEl("button", {
      cls: "iflow-conversation-trigger",
      attr: {
        "aria-expanded": "false",
        "aria-haspopup": "listbox"
      }
    });
    this.conversationTitleEl = trigger.createSpan({
      cls: "iflow-conversation-title",
      text: t().ui.newConversation
    });
    const meta = trigger.createSpan({ cls: "iflow-conversation-meta", text: t().ui.noMessages });
    const chevron = trigger.createDiv({ cls: "iflow-conversation-chevron" });
    chevron.innerHTML = `
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<polyline points="6 9 12 15 18 9"></polyline>
			</svg>
		`;
    const newBtn = selector.createEl("button", {
      cls: "iflow-new-conversation-btn",
      text: "+"
    });
    newBtn.onclick = () => this.createNewConversation();
    const panel = selector.createDiv({ cls: "iflow-conversation-panel hidden" });
    const searchBox = panel.createDiv({ cls: "iflow-conversation-search" });
    const searchInput = searchBox.createEl("input", {
      type: "text",
      placeholder: t().ui.searchConversations
    });
    const list = panel.createDiv({ cls: "iflow-conversation-list" });
    this.renderConversationList(list);
    this.updateConversationMeta(meta);
    this.conversationTrigger = trigger;
    this.conversationPanel = panel;
    this.conversationList = list;
    this.conversationMeta = meta;
    trigger.onclick = (e) => {
      e.stopPropagation();
      this.toggleConversationPanel();
    };
    searchInput.addEventListener("input", (e) => {
      const target = e.target;
      this.renderConversationList(list, target.value);
    });
    document.addEventListener("click", (e) => {
      if (this.showConversationPanel && !selector.contains(e.target)) {
        this.closeConversationPanel();
      }
    });
  }
  renderConversationList(listContainer, searchQuery = "") {
    listContainer.empty();
    const state = this.conversationService.getState();
    const filteredConversations = state.conversations.filter(
      (c) => c.title.toLowerCase().includes(searchQuery.toLowerCase())
    );
    filteredConversations.sort((a, b) => b.updatedAt - a.updatedAt);
    const now = /* @__PURE__ */ new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const yesterday = new Date(today.getTime() - 24 * 60 * 60 * 1e3);
    const thisWeek = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1e3);
    const groups = [
      { label: t().ui.today, conversations: [] },
      { label: t().ui.yesterday, conversations: [] },
      { label: t().ui.thisWeek, conversations: [] },
      { label: t().ui.older, conversations: [] }
    ];
    filteredConversations.forEach((conv) => {
      const date = new Date(conv.updatedAt);
      if (date >= today) {
        groups[0].conversations.push(conv);
      } else if (date >= yesterday) {
        groups[1].conversations.push(conv);
      } else if (date >= thisWeek) {
        groups[2].conversations.push(conv);
      } else {
        groups[3].conversations.push(conv);
      }
    });
    groups.forEach((group) => {
      if (group.conversations.length > 0) {
        listContainer.createDiv({
          cls: "iflow-conversation-group-label",
          text: group.label
        });
        group.conversations.forEach((conv) => {
          this.renderConversationItem(listContainer, conv);
        });
      }
    });
    if (filteredConversations.length === 0) {
      listContainer.createDiv({
        cls: "iflow-conversation-empty",
        text: searchQuery ? t().ui.noConversationsFound : t().ui.noConversations
      });
    }
  }
  renderConversationItem(container, conversation) {
    const item = container.createDiv({
      cls: `iflow-conversation-item ${conversation.id === this.currentConversationId ? "active" : ""}`
    });
    const info = item.createDiv({ cls: "iflow-conversation-item-info" });
    const title = info.createDiv({
      cls: "iflow-conversation-item-title",
      text: conversation.title
    });
    const meta = info.createDiv({ cls: "iflow-conversation-item-meta" });
    meta.createSpan({ text: `${conversation.messages.length} ${t().ui.messages}` });
    const time = item.createDiv({
      cls: "iflow-conversation-item-time",
      text: this.formatTime(conversation.updatedAt)
    });
    const deleteBtn = item.createEl("button", {
      cls: "iflow-conversation-item-delete",
      text: "\xD7"
    });
    deleteBtn.onclick = (e) => {
      e.stopPropagation();
      this.deleteConversation(conversation.id);
    };
    item.onclick = () => {
      this.switchConversation(conversation.id);
    };
  }
  formatTime(timestamp) {
    const date = new Date(timestamp);
    const now = /* @__PURE__ */ new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 6e4);
    const diffHours = Math.floor(diffMs / 36e5);
    if (diffMins < 1) return t().ui.now;
    if (diffMins < 60) return format(t().ui.minutesAgo, { n: diffMins });
    if (diffHours < 24) return format(t().ui.hoursAgo, { n: diffHours });
    return date.toLocaleDateString();
  }
  updateConversationMeta(meta) {
    const current = this.conversationService.getCurrentConversation();
    if (current) {
      meta.textContent = `${current.messages.length} ${t().ui.messages}`;
    } else {
      meta.textContent = t().ui.noMessages;
    }
  }
  onConversationChange() {
    if (this.isStreaming) {
      console.log("[iFlow Chat] Skipping reload during streaming");
      this.updateConversationUI();
      return;
    }
    if (this.isLoadingMessages) {
      console.log("[iFlow Chat] Already loading, skipping");
      return;
    }
    this.isLoadingMessages = true;
    const state = this.conversationService.getState();
    this.currentConversationId = state.currentConversationId;
    const current = this.conversationService.getCurrentConversation();
    if (this.conversationTitleEl && current) {
      this.conversationTitleEl.textContent = current.title;
    }
    this.loadMessagesFromConversation();
    const list = this.conversationList;
    if (list) {
      this.renderConversationList(list);
    }
    const meta = this.conversationMeta;
    if (meta) {
      this.updateConversationMeta(meta);
    }
    this.isLoadingMessages = false;
  }
  updateConversationUI() {
    const current = this.conversationService.getCurrentConversation();
    if (!current) return;
    if (this.conversationTitleEl) {
      this.conversationTitleEl.textContent = current.title;
    }
    const meta = this.conversationMeta;
    if (meta) {
      this.updateConversationMeta(meta);
    }
    const list = this.conversationList;
    if (list) {
      this.renderConversationList(list);
    }
  }
  createNewConversation() {
    this.closeConversationPanel();
    this.conversationService.newConversation(
      this.currentModel,
      this.currentMode,
      this.thinkingEnabled
    );
  }
  toggleConversationPanel() {
    this.showConversationPanel = !this.showConversationPanel;
    this.updateConversationPanelVisibility();
  }
  closeConversationPanel() {
    this.showConversationPanel = false;
    this.updateConversationPanelVisibility();
  }
  updateConversationPanelVisibility() {
    const trigger = this.conversationTrigger;
    const panel = this.conversationPanel;
    if (trigger) {
      trigger.setAttribute("aria-expanded", this.showConversationPanel ? "true" : "false");
    }
    if (panel) {
      if (this.showConversationPanel) {
        panel.removeClass("hidden");
        const searchInput = panel.querySelector(".iflow-conversation-search input");
        searchInput == null ? void 0 : searchInput.focus();
      } else {
        panel.addClass("hidden");
      }
    }
  }
  switchConversation(conversationId) {
    this.conversationService.switchConversation(conversationId);
    this.closeConversationPanel();
  }
  deleteConversation(conversationId) {
    this.conversationService.deleteConversation(conversationId);
  }
  loadMessagesFromConversation() {
    this.messagesContainer.empty();
    this.isStreaming = false;
    this.currentMessage = "";
    const current = this.conversationService.getCurrentConversation();
    if (!current) {
      this.addWelcomeMessage();
      this.messages = [];
      return;
    }
    this.messages = [];
    this.messageListView.loadConversation(current.messages);
    current.messages.forEach((msg) => {
      this.messages.push({ role: msg.role, content: msg.content, id: msg.id });
    });
    this.scrollToBottom();
  }
  // ============================================
  // Update available options from iFlow CLI
  // ============================================
  updateAvailableModels(models) {
    this.availableModels = models;
  }
  updateAvailableModes(modes) {
    this.availableModes = modes;
  }
};

// src/app/settingsService.ts
var SettingsService = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async load() {
    await this.plugin.loadSettings();
    return this.plugin.settings;
  }
  get() {
    return this.plugin.settings;
  }
  async update(partial) {
    this.plugin.settings = { ...this.plugin.settings, ...partial };
    await this.plugin.saveSettings();
    return this.plugin.settings;
  }
};

// src/app/sdkProcessManager.ts
var SdkProcessManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async ensureRunning(forceRestart = false) {
    const success = await this.plugin.ensureSdkRunning(forceRestart);
    return { success };
  }
  async start() {
    const success = await this.plugin.startSdk();
    return { success };
  }
};

// src/app/pluginBootstrap.ts
function bootstrap(plugin) {
  return {
    settingsService: new SettingsService(plugin),
    sdkProcessManager: new SdkProcessManager(plugin)
  };
}

// src/main.ts
var { spawn } = require("child_process");
var path = require("path");
var DEFAULT_SETTINGS = {
  iflowPort: 8090,
  iflowTimeout: 6e4,
  enableAutoScroll: true,
  excludedTags: ["private", "sensitive"],
  language: "zh-CN",
  autoAttachFile: true,
  lastUsedModel: "glm-4.7",
  lastUsedMode: "default",
  lastUsedThinking: false,
  autoStartSdk: true
  // Enabled by default
};
var IFlowPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.chatView = null;
    this.sdkProcess = null;
    // Keep reference to SDK process
    this.runtime = null;
  }
  async onload() {
    console.log("Loading iFlow for Obsidian plugin");
    await this.loadSettings();
    initI18n(this.settings.language);
    this.iflowService = new IFlowService(this.settings.iflowPort, this.settings.iflowTimeout, this.app);
    this.runtime = bootstrap(this);
    this.registerView(
      VIEW_TYPE_IFLOW_CHAT,
      (leaf) => this.chatView = new IFlowChatView(leaf, this, this.iflowService)
    );
    this.addRibbonIcon("message-square", "Open iFlow Chat", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-iflow-chat",
      name: "Open iFlow Chat",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "open-iflow-chat-with-selection",
      name: "Open iFlow Chat with Selection",
      checkCallback: (checking) => {
        var _a;
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        const selection = (_a = activeView == null ? void 0 : activeView.editor) == null ? void 0 : _a.getSelection();
        if (selection) {
          if (!checking) {
            this.activateView();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "restart-iflow-sdk",
      name: "\u91CD\u542F iFlow SDK",
      callback: () => this.ensureSdkRunning(true)
    });
    this.addSettingTab(new IFlowSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(async () => {
      if (this.settings.autoStartSdk) {
        await this.ensureSdkRunning();
      }
      this.activateView();
    });
  }
  /**
   * Ensure iFlow SDK is running, start it if not
   */
  async ensureSdkRunning(forceRestart = false) {
    const port = this.settings.iflowPort;
    const isConnected = await this.iflowService.checkConnection();
    if (isConnected && !forceRestart) {
      console.log("[iFlow] SDK already running on port", port);
      return true;
    }
    new import_obsidian3.Notice("\u6B63\u5728\u542F\u52A8 iFlow SDK...");
    const started = await this.startSdk();
    if (started) {
      new import_obsidian3.Notice("iFlow SDK \u542F\u52A8\u6210\u529F\uFF01");
    } else {
      new import_obsidian3.Notice("iFlow SDK \u542F\u52A8\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u662F\u5426\u5DF2\u5B89\u88C5 iflow CLI");
    }
    return started;
  }
  /**
   * Start iFlow SDK process
   */
  async startSdk() {
    const port = this.settings.iflowPort;
    return new Promise((resolve) => {
      var _a, _b;
      try {
        console.log("[iFlow] Starting SDK on port", port);
        const isWindows = process.platform === "win32";
        if (isWindows) {
          this.sdkProcess = spawn("cmd.exe", [
            "/c",
            `iflow --experimental-acp --port ${port} --stream`
          ], {
            detached: true,
            shell: false,
            windowsHide: true
          });
        } else {
          this.sdkProcess = spawn("iflow", [
            "--experimental-acp",
            "--port",
            String(port),
            "--stream"
          ], {
            detached: true
          });
        }
        this.sdkProcess.on("error", (err) => {
          console.error("[iFlow] SDK process error:", err);
          resolve(false);
        });
        (_a = this.sdkProcess.stdout) == null ? void 0 : _a.on("data", (data) => {
          console.log("[iFlow SDK]", data.toString());
        });
        (_b = this.sdkProcess.stderr) == null ? void 0 : _b.on("data", (data) => {
          console.error("[iFlow SDK Error]", data.toString());
        });
        setTimeout(async () => {
          const connected = await this.iflowService.checkConnection();
          resolve(connected);
        }, 3e3);
      } catch (error) {
        console.error("[iFlow] Failed to start SDK:", error);
        resolve(false);
      }
    });
  }
  onunload() {
    console.log("Unloading iFlow for Obsidian plugin");
    this.iflowService.dispose();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_IFLOW_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_IFLOW_CHAT, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.iflowService.updateConfig(this.settings.iflowPort, this.settings.iflowTimeout);
  }
  getActiveFile() {
    return this.app.workspace.getActiveFile();
  }
  getVaultPath() {
    return this.app.vault.adapter.basePath;
  }
};
var IFlowSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const settings = t().settings;
    new import_obsidian3.Setting(containerEl).setName(settings.language).setDesc(settings.languageDesc).addDropdown((dropdown) => dropdown.addOption("zh-CN", "\u4E2D\u6587\u7B80\u4F53").addOption("en-US", "English").setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
      initI18n(value);
      this.display();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u81EA\u52A8\u542F\u52A8 SDK").setDesc("\u63D2\u4EF6\u52A0\u8F7D\u65F6\u81EA\u52A8\u542F\u52A8 iFlow SDK\uFF08\u63A8\u8350\u5F00\u542F\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoStartSdk).onChange(async (value) => {
      this.plugin.settings.autoStartSdk = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u91CD\u542F SDK").setDesc("\u624B\u52A8\u91CD\u542F iFlow SDK \u670D\u52A1").addButton((button) => button.setButtonText("\u91CD\u542F").onClick(async () => {
      button.setButtonText("\u542F\u52A8\u4E2D...");
      button.setDisabled(true);
      const success = await this.plugin.startSdk();
      button.setButtonText("\u91CD\u542F");
      button.setDisabled(false);
      if (success) {
        new import_obsidian3.Notice("SDK \u91CD\u542F\u6210\u529F\uFF01");
        this.display();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName(settings.port).setDesc(settings.portDesc).addText((text) => text.setValue(String(this.plugin.settings.iflowPort)).onChange(async (value) => {
      const port = parseInt(value);
      if (!isNaN(port) && port > 0 && port < 65536) {
        this.plugin.settings.iflowPort = port;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName(settings.timeout).setDesc(settings.timeoutDesc).addText((text) => text.setValue(String(this.plugin.settings.iflowTimeout)).onChange(async (value) => {
      const timeout = parseInt(value);
      if (!isNaN(timeout) && timeout > 0) {
        this.plugin.settings.iflowTimeout = timeout;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName(settings.autoScroll).setDesc(settings.autoScrollDesc).addToggle((toggle) => toggle.setValue(this.plugin.settings.enableAutoScroll).onChange(async (value) => {
      this.plugin.settings.enableAutoScroll = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(settings.autoAttachFile).setDesc(settings.autoAttachFileDesc).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoAttachFile).onChange(async (value) => {
      this.plugin.settings.autoAttachFile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName(settings.excludedTags).setDesc(settings.excludedTagsDesc).addText((text) => text.setValue(this.plugin.settings.excludedTags.join(", ")).onChange(async (value) => {
      this.plugin.settings.excludedTags = value.split(",").map((tag) => tag.trim()).filter((tag) => tag.length > 0);
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: settings.cliRequirements });
    containerEl.createEl("p", {
      text: settings.cliRequirementsDesc
    });
    const statusDiv = containerEl.createEl("div", { cls: "iflow-status" });
    statusDiv.createEl("p", { text: settings.connectionStatus });
    const statusText = statusDiv.createEl("span", { cls: "iflow-status-text" });
    statusText.textContent = settings.checking;
    this.plugin.iflowService.checkConnection().then((connected) => {
      statusText.textContent = connected ? settings.connected : settings.disconnected;
      statusText.className = "iflow-status-text " + (connected ? "connected" : "disconnected");
    });
  }
};
